### ISSUE TITLE
some problem about running python3 megaface_eval.py

### ISSUE THREAD

**Issue by ReverseSystem001** [foamliu/InsightFace-v3#10]
['../bin/Identification', '../models/jb_identity.bin', 'path', 'results/otherFiles/facescrub_features_0', 'results/otherFiles/facescrub_features_0', 'results/otherFiles/facescrub_facescrub_0.bin']
../bin/Identification: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ../bin/Identification)

**Comment by foamliu** [comment]
Please make sure you've done this step:
"Download Linux DevKit from MagaFace WebSite then extract to megaface folder"
