### ISSUE TITLE
Is there a reason why arcMargin model is trained seperately ?

### ISSUE THREAD

**Issue by bmabir17** [foamliu/InsightFace-v3#11]
In line
https://github.com/foamliu/InsightFace-PyTorch/blob/d05cf00b54cac1bac211679157432aaa1a821c4f/train.py#L42-L43
and  https://github.com/foamliu/InsightFace-PyTorch/blob/d05cf00b54cac1bac211679157432aaa1a821c4f/train.py#L116-L117 

Can someone please expain why resnet and arcMargin model is trained seperately?

Is there any difference if do the following and do this?
```python
        resnet = models.resnet34(pretrained=True)
        modules = list(resnet.children())[:-1]      # delete the last fc layer.
        self.backbone = nn.Sequential(*modules)
        self.metric_fc = MerginFC(
            self.in_features,
            self.NUM_CLASS,
            xface_product=AddMarginProduct,
            m=self.m).cuda()
```

And define the following in my forward function
```python 
        embed = self.backbone(x)
        embed = embed.view(-1, self.in_features)
        feature = self.metric_fc(embed, labels)

```

**Comment by foamliu** [comment]
More convinient in writting inference code.
