### ISSUE TITLE
Can't get attribute 'ArcMarginModel'

### ISSUE THREAD

**Issue by aligoglos** [foamliu/InsightFace-v3#2]
When I tried to load model in `megaface_utils.gen_feature`  this error occured :
`AttributeError: Can't get attribute 'ArcMarginModel' on <module 'models' (namespace)>`

**Comment by foamliu** [comment]
This is fixed, please reopen if otherwise.

**Comment by sumitgupta153** [comment]
Where is the fix for this issue?
 AttributeError: Can't get attribute 'ArcMarginModel' on <module 'models' (namespace)>
