### ISSUE TITLE
Preprocessing codes?

### ISSUE THREAD

**Issue by ufoym** [foamliu/InsightFace-v3#6]
For training data preparation, the `README.md` shows that there is an image alignment phase containing the following steps:
- Face detection(Retinaface mobilenet0.25).
- Face alignment(similar transformation).
- Central face selection.
- Resize -> 112x112.

But from the following scripts as well as `train.py`, I cannot find the corresponding codes. 
```
$ python extract.py
$ python pre_process.py
```

Could you please show me how to preprocess the extracted images before training?

**Comment by foamliu** [comment]
The dataset is aligned (with retinaface) already.
