### ISSUE TITLE
Comparison to original mxnet

### ISSUE THREAD

**Issue by xsacha** [foamliu/InsightFace-v3#7]
I notice this version says only 97.4% megaface. The original mxnet states 98.5+%.

What is the reason for the difference? Do you know?

**Comment by foamliu** [comment]
No, I don't.

**Comment by ShiinaMitsuki** [comment]
maybe the mxnet version uses combine margin loss(m1,m2,m3) instead of additive margin loss(m2 only)

**Comment by foamliu** [comment]
mxnet version supports multiple loss types but the default one is still additive margin loss.
