### ISSUE TITLE
Detail about the training dataset

### ISSUE THREAD

**Issue by ShiinaMitsuki** [foamliu/InsightFace-v3#9]
感谢大佬提供的repo，想问一下训练数据集是 原版的 ms1m数据集吗？ 还是insightface官方repo给出的 [MS1M-ArcFace](https://pan.baidu.com/s/1S6LJZGdqcZRle1vlcMzHOQ) 或者 [MS1M-IBUG](https://pan.baidu.com/s/1nxmSCch)? 
先谢谢了🙏

**Comment by foamliu** [comment]
是insightface官方repo给出 faces_emore.zip
